networks:
    tg-bot:
      driver: bridge

volumes: 
    minio:
    redis:

services:
    redis:
        image: bitnami/redis
        ports:
            - "7000:7000"
        environment:
        - REDIS_PORT_NUMBER=${REDIS_PORT}
        - ALLOW_EMPTY_PASSWORD=yes
            #volumes:
            #- redis:/bitnami/redis/data:rw
        networks:
        - tg-bot
    minio:
        image: bitnami/minio:2021.6.17-debian-10-r36
        ports:
            - "9000:9000"
            #volumes:
            #- minio:/data:rw
        environment:
        - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
        - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
        - BITNAMI_DEBUG=true
        networks:
        - tg-bot