networks:
    tg-bot:
      driver: bridge

volumes: 
    minio:
    redis:

services:
    redis:
        image: bitnami/redis
        ports:
        - "7000:7000"
        environment:
        - REDIS_PORT_NUMBER=${REDIS_PORT}
        - ALLOW_EMPTY_PASSWORD=yes
        #volumes:
        #- redis:/bitnami/redis/data:rw
        networks:
        - tg-bot
    app:
        depends_on:
            - redis
        build:
            context: "./"
        env_file: .env
        command: celery -A app worker -B
        networks:
        - tg-bot