version: "3.8"
networks:
    tg-bot-overlay:
      driver: overlay
      attachable: true 

volumes: 
    minio:
    redis:

services:
    redis:
        image: bitnami/redis
        expose:
        - "7000"
        environment:
        - REDIS_PORT_NUMBER=7000
        - ALLOW_EMPTY_PASSWORD=yes
        volumes:
        - redis:/bitnami/redis/data:rw
        networks:
        - tg-bot-overlay
    app:
        depends_on:
            - redis
        image: vktotgbot:1.0
        env_file: .env
        command: celery -A app worker -B
        networks:
        - tg-bot-overlay
